export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Premium Bank',
    headLine: 'Unlimited Transactions with zero fees',
    description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    buttonLabel:'Get Started',
    imgStart: false,
    img: '/images/svg-1.svg',
    alt: 'Car',
    dark:true,
    primary:true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Unlimited Access',
    headLine: 'Unlimited Transactions with zero fees',
    description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    buttonLabel:'Lear More',
    imgStart: true,
    img: '/images/svg-3.svg',
    alt: 'Piggy Bank',
    dark:false,
    primary:false,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our team',
    headLine: 'Creating an account is extremely easy',
    description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    buttonLabel:'Start Now',
    imgStart: false,
    img: '/images/svg-4.svg',
    alt: 'Papers',
    dark:false,
    primary:false,
    darkText:true,
};